# Site settings
title: Gustavo Lizárraga
name: Gustavo Lizárraga
description: "Auth0 Ambassador"
biography-1: "Organizer GDG Android Bolivia" 
biography-2: "Android and iOS Developer. Trainer. Speaker." 
biography-3: "I like it technologies as Firebase, Kotlin lover, Machine Learning, Flutter and more."
baseurl: ""
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  Gusn8
facebook_username: Gusn8
twitter_username: Gusn8_
linkedin_username: Gusn8
instagram_username:  Gusn8
messenger_username:  Gusn8
whatsapp_number: 591 77752810
blog_url: "www.miramicodigo.com"
email: lizarraga.gux@gmail.com

avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "imgs/avatar.jpg"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
